# https://medium.com/@vinoji2005/day-11-gitlab-ci-cd-for-docker-based-workflows-e5cc50ae8f49
stages:
  - build
  - test
  - deploy

build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t registry.gitlab.com/your-username/your-project:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/your-username/your-project:$CI_COMMIT_SHA
  only:
    - main

  git add .gitlab-ci.yml
  git commit -m "Set up Docker image building"
  git push origin main

test-docker-image:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run registry.gitlab.com/your-username/your-project:$CI_COMMIT_SHA pytest
  
  git add .gitlab-ci.yml
  git commit -m "Add Docker test job"
  git push origin main

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t your-dockerhub-username/your-project:$CI_COMMIT_SHA .
  - docker push your-dockerhub-username/your-project:$CI_COMMIT_SHA

deploy-to-kubernetes:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config set-cluster your-cluster --server=$KUBE_SERVER
    - kubectl config set-credentials your-credentials --token=$KUBE_TOKEN
    - kubectl set image deployment/your-deployment your-container=registry.gitlab.com/your-username/your-project:$CI_COMMIT_SHA

  git add .gitlab-ci.yml
  git commit -m "Deploy Docker container to Kubernetes"
  git push origin main

  git add .gitlab-ci.yml
  git commit -m "Add Kubernetes rollback mechanism"
  git push origin main

# Optional with Swarm
deploy-to-swarm:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker service update --image registry.gitlab.com/your-username/your-project:$CI_COMMIT_SHA your-swarm-service
  
  git add .gitlab-ci.yml
  git commit -m "Deploy Docker container to Docker Swarm"
  git push origin main