stages: build
  containerize

cache:
  key: $CI_BUILD_REF
  paths:
    - index.js

build:
  stage: build
  image: node:8
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - server.js
    expire_in: 1 hour

containerize:
  stage: containerize
  image: docker:<tag>
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t user/<test-devops-image>:latest
    - docker push user/<test-devops-image>:latest