name: Deploy using Helm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t <test-devops-imageRepository>:${{ github.sha }} .
        docker push <test-devops-imageRepository>:${{ github.sha }}

    - name: Set up Kubectl
      uses: aws/setup-kubectl@v3
      with:
        version: 'vX.X.X' 

    - name: Install Helm
      uses: aws/setup-helm@v1

    - name: Create kubeconfig file
      run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig

    - name: Deploy to Kubernetes using Helm
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
       cd Github-with-helm/Github       
       helm upgrade --install helm-deploy-test helm-deploy \
       --set image.repository=<test-devops-image-repository" \
       --set image.tag=${{ github.sha }} \
       --namespace default