FROM node:20-slim

WORKDIR /app

# Installazione pnpm
RUN npm install -g pnpm

# Copia del file 
COPY package.json pnpm-lock.yaml tsconfig.json /app

# Copia codice sorgente
COPY src /app/src

# Intallazione dipendenze
RUN pnpm install

# Build del codice TypeScript
RUN pnpm build

# Run della action
ENTRYPOINT ["node", ".index.js"]