name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - staging

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
# Checking Out the Code
      - name: Checkout Code                   
        uses: actions/checkout@v3
# Setting Up Docker Buildx
      - name: Set up Docker Buildx            
        uses: docker/setup-buildx-action@v2
# Configuring and Logging into the Docker Registry
      - name: Add Registry to /etc/hosts
        run: |
          echo "${{ secrets.HOSTS_ENTRY }}" | sudo tee -a /etc/hosts

      - name: Configure Docker for Insecure Registry
        run: |
          sudo mkdir -p /etc/docker
          echo '{ "insecure-registries": ["https://harbor.example.com"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: test-devops.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
# Tagging with a Date-Time-Based Version
      - name: Generate Date-Time-Based Tag
        id: generate_tag
        run: |
          new_version=$(date -u +"v%Y.%m.%d.%H%M%S")
          echo "Generated tag: $new_version"
          echo "version=$new_version" >> $GITHUB_ENV
# Building and Pushing the Docker Image      
      - name: Build Docker Image
        run: |
          PROJECT_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          docker build -f .docker/Dockerfile \
          -t harbor.example.com/${{ vars.PROJECT_NAME }}/$PROJECT_NAME:${{ env.version }} -t harbor.example.com/${{ vars.PROJECT_NAME }}/$PROJECT_NAME:latest .
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Push Docker Image
        run: |
          PROJECT_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          docker push harbor.example.com/${{ vars.PROJECT_NAME }}/$PROJECT_NAME:${{ env.version }}
          docker push harbor.example.com/${{ vars.PROJECT_NAME }}/$PROJECT_NAME:latest
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
# Deploying to a Remote Server
      - name: Deploy to Remote Server
        if: success()
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_COMMANDS: ${{ secrets.DEPLOY_COMMANDS }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${SSH_USERNAME}@${SSH_HOST} "${DEPLOY_COMMANDS}"
        shell: bash